# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\alex\Documents\Facultate\IOC\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1084, 718)
        MainWindow.setMinimumSize(QtCore.QSize(971, 648))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 500, 181, 51))
        self.pushButton.setStyleSheet("font: 18pt \"Times New Roman\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(760, 500, 181, 51))
        self.pushButton_2.setStyleSheet("font: 75 20pt \"Times New Roman\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(430, 410, 221, 51))
        self.pushButton_3.setStyleSheet("font: 75 20pt \"Times New Roman\";\n"
"\n"
"QPushButton{\n"
"        border-style: outset;\n"
"        border-width: 2px;\n"
"           border-radius: 10px;\n"
"            border-color: beige;\n"
"            font: bold 14px;\n"
"        min-width: 10em;\n"
"        padding: 6px;\n"
"} \n"
"\n"
"\n"
"QPushButton:hover\n"
"{ \n"
"           border-style: inset;\n"
"}\n"
"QPushButton:pressed\n"
"{ \n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"} \n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(760, 590, 181, 51))
        self.pushButton_4.setStyleSheet("font: 75 20pt \"Times New Roman\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(80, 80, 421, 281))
        self.textEdit.setStyleSheet("font: 20pt \"Times New Roman\";")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(580, 80, 421, 281))
        self.textEdit_2.setStyleSheet("font: 20pt \"Times New Roman\";")
        self.textEdit_2.setObjectName("textEdit_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(80, 410, 311, 51))
        self.comboBox.setStyleSheet("font: 18pt \"Times New Roman\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(690, 410, 311, 51))
        self.comboBox_2.setStyleSheet("font: 18pt \"Times New Roman\";")
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(430, 500, 221, 51))
        self.pushButton_5.setStyleSheet("font: 75 20pt \"Times New Roman\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setEnabled(True)
        self.checkBox.setGeometry(QtCore.QRect(170, 590, 101, 41))
        self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.checkBox.setStyleSheet("QCheckBox::indicator{     \n"
"    width: 75px; \n"
"    height: 75px; \n"
"} \n"
"\n"
"")
        self.checkBox.setText("")
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 590, 91, 41))
        self.label.setStyleSheet("font: 14pt \"Times New Roman\";")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_QT = QtWidgets.QAction(MainWindow)
        self.actionAbout_QT.setObjectName("actionAbout_QT")
        self.actionDespre_Aplicatie = QtWidgets.QAction(MainWindow)
        self.actionDespre_Aplicatie.setObjectName("actionDespre_Aplicatie")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TRADUCERE"))
        self.pushButton.setText(_translate("MainWindow", "MIC"))
        self.pushButton_2.setText(_translate("MainWindow", "ASCULTĂ"))
        self.pushButton_3.setText(_translate("MainWindow", "TRADUCERE"))
        self.pushButton_4.setText(_translate("MainWindow", "AJUTOR"))
        self.pushButton_5.setText(_translate("MainWindow", "STERGE"))
        self.label.setText(_translate("MainWindow", "CULORI"))
        self.actionAbout_QT.setText(_translate("MainWindow", "Despre QT"))
        self.actionDespre_Aplicatie.setText(_translate("MainWindow", "Despre Aplicatie"))
import ResourceFile_rc
